### ISSUE TITLE
SDL2/SDL2.h missing

### ISSUE THREAD

**Issue by theSoberSobber** [gustavopezzi/2dphysics#2]
did you forget to push a few folders, cus it won't compile because of multiple missing files.
such a shame, it looked so cool to build and run

**Comment by gustavopezzi** [comment]
You need to have SDL already installed on your system before you build the project. You can do that easily on Linux with the apt package manager:

`**sudo apt install libsdl2-dev**`

**Comment by Kodecha** [comment]
In my C++ project, I include "SDL/SDL2.h"  due to the file structure. Check your file structure and compiler settings if you have already ensured you have downloaded and installed all necessary files.
